require("plugins")
-- looks and functionality
require("colours")
require("mappings")
require("diag")
-- code parsing/actions
require("lsp")
require("linting")
require("coc")
require("ts")
require("search")
require("telescope_multigrep")
require("lualine_python")
require("format")
require("snippet")
-- language specific configs
require("frontend")
require("elixir")
require("languages")
require("autocomplete")
require("sql")
require("ai_tools")
-- require("vimtex")
